const express = require('express');
const router = express.Router();
const Analytics = require('../models/Analytics');
// const dummyData = require('../data/userData');

// Dummy data
const dummyData = [
    {
      user: {
        name: 'John Doe',
        category: 'Technology',
        bio: 'Tech Enthusiast',
        contact: 'john.doe@example.com',
        links: [{ label: 'Website', url: 'https://example.com' }],
      },
      followers: 1000,
      following: 150,
      posts: 200,
      accountReached: 5000,
      accountEngaged: 3000,
      contentShared: 100,
      adsRun: 20,
      activePromotions: 5,
      totalStories: 50,
      totalFollows: 800,
      totalPosts: 200,
      totalSaves: 300,
      totalComments: 150,
      totalShares: 75,
    },
    // Add 9 more user data objects here
    {
      user: {
        name: 'Jane Smith',
        category: 'Lifestyle',
        bio: 'Lifestyle Blogger',
        contact: 'jane.smith@example.com',
        links: [{ label: 'Blog', url: 'https://janesblog.com' }],
      },
      followers: 2000,
      following: 300,
      posts: 350,
      accountReached: 10000,
      accountEngaged: 7000,
      contentShared: 200,
      adsRun: 30,
      activePromotions: 8,
      totalStories: 100,
      totalFollows: 1500,
      totalPosts: 350,
      totalSaves: 600,
      totalComments: 300,
      totalShares: 150,
    },
    {
      user: {
        name: 'Michael Johnson',
        category: 'Fitness',
        bio: 'Fitness Trainer',
        contact: 'michael.johnson@example.com',
        links: [{ label: 'Instagram', url: 'https://instagram.com/michaeljohnson' }],
      },
      followers: 5000,
      following: 100,
      posts: 500,
      accountReached: 15000,
      accountEngaged: 12000,
      contentShared: 300,
      adsRun: 40,
      activePromotions: 10,
      totalStories: 200,
      totalFollows: 3000,
      totalPosts: 500,
      totalSaves: 900,
      totalComments: 450,
      totalShares: 225,
    },
    {
      user: {
        name: 'Emily Davis',
        category: 'Travel',
        bio: 'Travel Blogger',
        contact: 'emily.davis@example.com',
        links: [{ label: 'YouTube', url: 'https://youtube.com/emilydavis' }],
      },
      followers: 3000,
      following: 200,
      posts: 400,
      accountReached: 12000,
      accountEngaged: 9000,
      contentShared: 250,
      adsRun: 25,
      activePromotions: 6,
      totalStories: 150,
      totalFollows: 2400,
      totalPosts: 400,
      totalSaves: 750,
      totalComments: 350,
      totalShares: 175,
    },
    {
      user: {
        name: 'David Brown',
        category: 'Fashion',
        bio: 'Fashion Designer',
        contact: 'david.brown@example.com',
        links: [{ label: 'Website', url: 'https://davidbrown.com' }],
      },
      followers: 4000,
      following: 250,
      posts: 450,
      accountReached: 13000,
      accountEngaged: 9500,
      contentShared: 280,
      adsRun: 28,
      activePromotions: 7,
      totalStories: 175,
      totalFollows: 2700,
      totalPosts: 450,
      totalSaves: 850,
      totalComments: 400,
      totalShares: 200,
    },
    {
      user: {
        name: 'Sophia Martinez',
        category: 'Food',
        bio: 'Food Blogger',
        contact: 'sophia.martinez@example.com',
        links: [{ label: 'Blog', url: 'https://sophiablog.com' }],
      },
      followers: 3500,
      following: 220,
      posts: 380,
      accountReached: 12500,
      accountEngaged: 9300,
      contentShared: 260,
      adsRun: 26,
      activePromotions: 6,
      totalStories: 160,
      totalFollows: 2550,
      totalPosts: 380,
      totalSaves: 800,
      totalComments: 380,
      totalShares: 190,
    },
    {
      user: {
        name: 'Chris Wilson',
        category: 'Gaming',
        bio: 'Pro Gamer',
        contact: 'chris.wilson@example.com',
        links: [{ label: 'Twitch', url: 'https://twitch.com/chriswilson' }],
      },
      followers: 4500,
      following: 180,
      posts: 470,
      accountReached: 14000,
      accountEngaged: 10000,
      contentShared: 320,
      adsRun: 32,
      activePromotions: 9,
      totalStories: 190,
      totalFollows: 3150,
      totalPosts: 470,
      totalSaves: 900,
      totalComments: 470,
      totalShares: 230,
    },
    {
      user: {
        name: 'Olivia Lee',
        category: 'Beauty',
        bio: 'Beauty Influencer',
        contact: 'olivia.lee@example.com',
        links: [{ label: 'Instagram', url: 'https://instagram.com/olivialee' }],
      },
      followers: 3200,
      following: 210,
      posts: 390,
      accountReached: 11000,
      accountEngaged: 8500,
      contentShared: 270,
      adsRun: 27,
      activePromotions: 6,
      totalStories: 170,
      totalFollows: 2700,
      totalPosts: 390,
      totalSaves: 750,
      totalComments: 390,
      totalShares: 185,
    },
    {
      user: {
        name: 'Daniel Garcia',
        category: 'Photography',
        bio: 'Professional Photographer',
        contact: 'daniel.garcia@example.com',
        links: [{ label: 'Portfolio', url: 'https://danielgarcia.com' }],
      },
      followers: 3700,
      following: 230,
      posts: 420,
      accountReached: 11500,
      accountEngaged: 8800,
      contentShared: 290,
      adsRun: 29,
      activePromotions: 7,
      totalStories: 180,
      totalFollows: 2850,
      totalPosts: 420,
      totalSaves: 800,
      totalComments: 420,
      totalShares: 210,
    },
    {
      user: {
        name: 'Laura Kim',
        category: 'Education',
        bio: 'Educational Content Creator',
        contact: 'laura.kim@example.com',
        links: [{ label: 'YouTube', url: 'https://youtube.com/laurakim' }],
      },
      followers: 3900,
      following: 240,
      posts: 430,
      accountReached: 11800,
      accountEngaged: 9000,
      contentShared: 300,
      adsRun: 30,
      activePromotions: 7,
      totalStories: 190,
      totalFollows: 2900,
      totalPosts: 430,
      totalSaves: 850,
      totalComments: 430,
      totalShares: 215,
    }
  ];
  
// Create dummy data in the database
router.post('/create-dummy', async (req, res) => {
  await Analytics.insertMany(dummyData);
  res.send('Dummy data created');
});

// Get analytics data
router.get('/', async (req, res) => {
  const analytics = await Analytics.find();
  res.json(analytics);
});

module.exports = router;
